{
	"bugzilla": {
		"description": "CVE-2018-11499 libsass: Use-after-free vulnerability in sass_context.cpp:handle_error() can lead to denial of service or other unspecified impact",
		"id": "1583182",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1583182"
	},
	"csaw": false,
	"cvss3": {
		"cvss3_base_score": "3.3",
		"cvss3_scoring_vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
		"status": "draft"
	},
	"cwe": "CWE-416",
	"details": [
		"A use-after-free vulnerability exists in handle_error() in sass_context.cpp in LibSass 3.4.x and 3.5.x through 3.5.4 that could be leveraged to cause a denial of service (application crash) or possibly unspecified other impact."
	],
	"name": "CVE-2018-11499",
	"public_date": "2018-05-02T00:00:00Z",
	"threat_severity": "Low"
}
