{
	"name": "CVE-2018-9146",
	"public_date": "2018-03-28T00:00:00Z",
	"bugzilla": {
		"description": "CVE-2018-9146 exiv2: out-of-bounds read in Exiv2::IptcData::printStructure in image.cpp",
		"id": "1564284",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1564284"
	},
	"cvss3": {
		"cvss3_base_score": "3.3",
		"cvss3_scoring_vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
		"status": "draft"
	},
	"cwe": "CWE-125",
	"details": [
		"This CVE ID has been rejected or withdrawn by its CVE Numbering Authority for the following reason: DO NOT USE THIS CANDIDATE NUMBER.  ConsultIDs: CVE-2017-17724.  Reason: This candidate is a reservation duplicate of CVE-2017-17724.  Notes: All CVE users should reference CVE-2017-17724 instead of this candidate.  All references and descriptions in this candidate have been removed to prevent accidental usage"
	],
	"statement": "This flaw was found to be a duplicate of CVE-2017-17724. Please see https://access.redhat.com/security/cve/CVE-2017-17724 for information about affected products and security errata.",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2018-9146\nhttps://nvd.nist.gov/vuln/detail/CVE-2018-9146"
	],
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"fix_state": "Not affected",
			"package_name": "exiv2",
			"product_name": "Red Hat Enterprise Linux 6"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Not affected",
			"package_name": "exiv2",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "exiv2",
			"product_name": "Red Hat Enterprise Linux 8"
		}
	],
	"csaw": false
}
