{
	"name": "CVE-2015-3982",
	"threat_severity": "Moderate",
	"public_date": "2015-05-20T00:00:00Z",
	"bugzilla": {
		"description": "django: incorrect session flushing in the cached_db backend",
		"id": "1221526",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1221526"
	},
	"cvss": {
		"cvss_base_score": "5.8",
		"cvss_scoring_vector": "AV:N/AC:M/Au:N/C:P/I:P/A:N",
		"status": "draft"
	},
	"cwe": "CWE-613",
	"details": [
		"The session.flush function in the cached_db backend in Django 1.8.x before 1.8.2 does not properly flush the session, which allows remote attackers to hijack user sessions via an empty string in the session key."
	],
	"statement": "Not vulnerable. The 1.8 version of Django is not shipped in any Red Hat product.",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2015-3982\nhttps://nvd.nist.gov/vuln/detail/CVE-2015-3982\nhttps://www.djangoproject.com/weblog/2015/may/20/security-release/"
	],
	"acknowledgement": "Red Hat would like to thank upstream Django project for reporting this issue.",
	"package_state": [
		{
			"cpe": "cpe:/a:redhat:openstack:5::el6",
			"fix_state": "Not affected",
			"package_name": "python-django",
			"product_name": "Red Hat Enterprise Linux OpenStack Platform 5 (Icehouse)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:6",
			"fix_state": "Not affected",
			"package_name": "python-django",
			"product_name": "Red Hat Enterprise Linux OpenStack Platform 6 (Juno)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:4",
			"fix_state": "Not affected",
			"package_name": "Django14",
			"product_name": "Red Hat OpenStack Platform 4"
		},
		{
			"cpe": "cpe:/a:rhel_sam:1",
			"fix_state": "Not affected",
			"package_name": "Django",
			"product_name": "Red Hat Subscription Asset Manager"
		}
	],
	"upstream_fix": "Django 1.8.2",
	"csaw": false
}
