{
	"acknowledgement": "Red Hat would like to thank oCERT for reporting this issue.",
	"affected_release": [
		{
			"advisory": "RHSA-2012:0745",
			"cpe": "cpe:/o:redhat:enterprise_linux:5",
			"package": "python-0:2.4.3-46.el5_8.2",
			"product_name": "Red Hat Enterprise Linux 5",
			"release_date": "2012-06-18T00:00:00Z"
		},
		{
			"advisory": "RHSA-2012:0744",
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"package": "python-0:2.6.6-29.el6_2.2",
			"product_name": "Red Hat Enterprise Linux 6",
			"release_date": "2012-06-18T00:00:00Z"
		}
	],
	"bugzilla": {
		"description": "hash table collisions CPU usage DoS (oCERT-2011-003)",
		"id": "750555",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=750555"
	},
	"csaw": false,
	"cvss": {
		"cvss_base_score": "5.0",
		"cvss_scoring_vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
		"status": "verified"
	},
	"details": [
		"Python before 2.6.8, 2.7.x before 2.7.3, 3.x before 3.1.5, and 3.2.x before 3.2.3 computes hash values without restricting the ability to trigger hash collisions predictably, which allows context-dependent attackers to cause a denial of service (CPU consumption) via crafted input to an application that maintains a hash table."
	],
	"name": "CVE-2012-1150",
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:4",
			"fix_state": "Will not fix",
			"package_name": "python",
			"product_name": "Red Hat Enterprise Linux 4"
		}
	],
	"public_date": "2011-12-28T00:00:00Z",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2012-1150\nhttps://nvd.nist.gov/vuln/detail/CVE-2012-1150"
	],
	"threat_severity": "Moderate"
}
