{
	"name": "CVE-2022-48565",
	"threat_severity": "Moderate",
	"public_date": "2023-08-22T00:00:00Z",
	"bugzilla": {
		"description": "python: XML External Entity in XML processing plistlib module",
		"id": "2240059",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2240059"
	},
	"cvss3": {
		"cvss3_base_score": "7.8",
		"cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
		"status": "draft"
	},
	"cwe": "CWE-611",
	"details": [
		"An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.",
		"A flaw was found in Python caused by improper handling of XML external entity (XXE) declarations by the plistlib module. By using a specially crafted XML content, an attacker could obtain sensitive information by disclosing files specified by parsing URI, and may cause denial of service by resource exhaustion."
	],
	"statement": "This vulnerability is classified as Moderate according to Red Hat's Severity Rating Classification, as in contrast to an Important severity rating, the conditions to exploit this vulnerability makes it highly improbable for a general remote use case to lead to arbitrary code execution or affect data integrity and the highest impact is data disclosure and application crash.\nThe versions of python as shipped with Red Hat Enterprise Linux 8 and Red Hat Enterprise Linux 9 either has fixed code or they just provide `symlinks` to the main `python3` component, which provides the interpreter of the Python programming language. Therefore, both Red Hat Enterprise Linux versions 8 and 9 are not affected.\nhttps://access.redhat.com/security/updates/classification",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2022-48565\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-48565"
	],
	"mitigation": {
		"lang": "en:us",
		"value": "The XML modules in python are not secure against erroneous or maliciously constructed data. If you need to parse untrusted or unauthenticated data, see the XML vulnerabilities and the defusedxml package sections. \nhttps://docs.python.org/dev/library/xml.html"
	},
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"fix_state": "Out of support scope",
			"impact": "moderate",
			"package_name": "python",
			"product_name": "Red Hat Enterprise Linux 6"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Out of support scope",
			"impact": "moderate",
			"package_name": "python",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Out of support scope",
			"impact": "moderate",
			"package_name": "python3",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Affected",
			"impact": "moderate",
			"package_name": "gimp:flatpak/python2",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Will not fix",
			"impact": "moderate",
			"package_name": "inkscape:flatpak/python2",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Affected",
			"impact": "moderate",
			"package_name": "python27:2.7/python2",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python3",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python3.11",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"impact": "moderate",
			"package_name": "python36:3.6/python36",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python39:3.9/python39",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Not affected",
			"package_name": "python3.11",
			"product_name": "Red Hat Enterprise Linux 9"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Not affected",
			"impact": "moderate",
			"package_name": "python3.9",
			"product_name": "Red Hat Enterprise Linux 9"
		},
		{
			"cpe": "cpe:/a:redhat:rhel_software_collections:3",
			"fix_state": "Not affected",
			"impact": "moderate",
			"package_name": "rh-python38-python",
			"product_name": "Red Hat Software Collections"
		}
	],
	"upstream_fix": "python 3.10.0a2, python 3.9.1rc, python 3.8.7rc1, python 3.7.10, python 3.6.13",
	"csaw": false
}
