{
	"name": "CVE-2021-31239",
	"threat_severity": "Moderate",
	"public_date": "2023-05-09T00:00:00Z",
	"bugzilla": {
		"description": "sqlite: denial of service via the appendvfs.c function",
		"id": "2207557",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2207557"
	},
	"cvss3": {
		"cvss3_base_score": "7.5",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
		"status": "draft"
	},
	"cwe": "CWE-125",
	"details": [
		"An issue found in SQLite SQLite3 v.3.35.4 that allows a remote attacker to cause a denial of service via the appendvfs.c function.",
		"A vulnerability was found in SQLite, where a segmentation fault occurs when appendvfs attempts to open a non-existent file. This flaw allows a remote attacker to cause a denial of service."
	],
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2021-31239\nhttps://nvd.nist.gov/vuln/detail/CVE-2021-31239\nhttps://www.sqlite.org/forum/forumpost/d9fce1a89b"
	],
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"fix_state": "Not affected",
			"package_name": "sqlite",
			"product_name": "Red Hat Enterprise Linux 6"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Not affected",
			"package_name": "sqlite",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "sqlite",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Not affected",
			"package_name": "sqlite",
			"product_name": "Red Hat Enterprise Linux 9"
		}
	],
	"upstream_fix": "sqlite 3.36.0",
	"csaw": false
}
