{
	"name": "CVE-2021-33642",
	"threat_severity": "Low",
	"public_date": "2022-05-28T00:00:00Z",
	"bugzilla": {
		"description": "byacc: an infinite loop occurs in next_inline() of the more_curly() function",
		"id": "2183009",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2183009"
	},
	"cvss3": {
		"cvss3_base_score": "3.3",
		"cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
		"status": "draft"
	},
	"cwe": "CWE-835",
	"details": [
		"When a file is processed, an infinite loop occurs in next_inline() of the more_curly() function."
	],
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2021-33642\nhttps://nvd.nist.gov/vuln/detail/CVE-2021-33642"
	],
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"fix_state": "Out of support scope",
			"package_name": "byacc",
			"product_name": "Red Hat Enterprise Linux 6"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Will not fix",
			"package_name": "byacc",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "byacc",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Not affected",
			"package_name": "byacc",
			"product_name": "Red Hat Enterprise Linux 9"
		}
	],
	"csaw": false
}
