{
	"name": "CVE-2021-21239",
	"threat_severity": "Moderate",
	"public_date": "2021-01-21T00:00:00Z",
	"bugzilla": {
		"description": "CVE-2021-21239 python-pysaml2: An improper verification of cryptographic signature",
		"id": "2007587",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2007587"
	},
	"cvss3": {
		"cvss3_base_score": "6.5",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
		"status": "draft"
	},
	"cwe": "CWE-347",
	"details": [
		"PySAML2 is a pure python implementation of SAML Version 2 Standard. PySAML2 before 6.5.0 has an improper verification of cryptographic signature vulnerability. Users of pysaml2 that use the default CryptoBackendXmlSec1 backend and need to verify signed SAML documents are impacted. PySAML2 does not ensure that a signed SAML document is correctly signed. The default CryptoBackendXmlSec1 backend is using the xmlsec1 binary to verify the signature of signed SAML documents, but by default xmlsec1 accepts any type of key found within the given document. xmlsec1 needs to be configured explicitly to only use only _x509 certificates_ for the verification process of the SAML document signature. This is fixed in PySAML2 6.5.0.",
		"A verification flaw was found in python-pysaml2, where it did not ensure that a signed SAML document was correctly signed. The default CryptoBackendXmlSec1 backend uses the xmlsec1 binary to verify the signature of signed SAML documents, but by default xmlsec1 accepts any type of key found within the given document. xmlsec1 must be configured explicitly to only use only x509 certificates for the verification process of the SAML document signature."
	],
	"statement": "All versions of Red Hat OpenStack Platform ship but do not use the flawed check-signature functionality of python-pysaml2. The impact for these products is therefore rated as having a security impact of Low and will not be updated at this time.",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2021-21239\nhttps://nvd.nist.gov/vuln/detail/CVE-2021-21239"
	],
	"mitigation": {
		"lang": "en:us",
		"value": "Mitigation for this issue is either not available or the currently available options do not meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability."
	},
	"package_state": [
		{
			"cpe": "cpe:/a:redhat:openstack:10",
			"fix_state": "Out of support scope",
			"impact": "low",
			"package_name": "python-pysaml2",
			"product_name": "Red Hat OpenStack Platform 10 (Newton)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:13",
			"fix_state": "Out of support scope",
			"impact": "low",
			"package_name": "python-pysaml2",
			"product_name": "Red Hat OpenStack Platform 13 (Queens)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:16.1",
			"fix_state": "Will not fix",
			"impact": "low",
			"package_name": "python-pysaml2",
			"product_name": "Red Hat OpenStack Platform 16.1"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:16.2",
			"fix_state": "Will not fix",
			"impact": "low",
			"package_name": "python-pysaml2",
			"product_name": "Red Hat OpenStack Platform 16.2"
		}
	],
	"upstream_fix": "python-pysaml2 6.5.0",
	"csaw": false
}
