{
	"name": "CVE-2013-4315",
	"threat_severity": "Low",
	"public_date": "2013-09-10T00:00:00Z",
	"bugzilla": {
		"description": "python-django: directory traversal with \"ssi\" template tag",
		"id": "1004969",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1004969"
	},
	"cvss": {
		"cvss_base_score": "2.1",
		"cvss_scoring_vector": "AV:N/AC:H/Au:S/C:P/I:N/A:N",
		"status": "verified"
	},
	"cwe": "CWE-22",
	"details": [
		"Directory traversal vulnerability in Django 1.4.x before 1.4.7, 1.5.x before 1.5.3, and 1.6.x before 1.6 beta 3 allows remote attackers to read arbitrary files via a file path in the ALLOWED_INCLUDE_ROOTS setting followed by a .. (dot dot) in a ssi template tag."
	],
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2013-4315\nhttps://nvd.nist.gov/vuln/detail/CVE-2013-4315\nhttps://www.djangoproject.com/weblog/2013/sep/10/security-releases-issued/"
	],
	"acknowledgement": "Red Hat would like to thank James Bennett (Django) for reporting this issue.",
	"affected_release": [
		{
			"advisory": "RHSA-2013:1521",
			"cpe": "cpe:/a:redhat:openstack:3::el6",
			"package": "Django14-0:1.4.8-1.el6ost",
			"product_name": "OpenStack 3 for RHEL 6",
			"release_date": "2013-11-14T00:00:00Z"
		}
	],
	"package_state": [
		{
			"cpe": "cpe:/a:redhat:openstack:4",
			"fix_state": "Affected",
			"package_name": "Django14",
			"product_name": "Red Hat OpenStack Platform 4"
		},
		{
			"cpe": "cpe:/a:rhel_sam:1",
			"fix_state": "Will not fix",
			"package_name": "Django",
			"product_name": "Red Hat Subscription Asset Manager"
		}
	],
	"upstream_fix": "Django 1.4.7, Django 1.5.3",
	"csaw": false
}
